
import os
import sys

try:
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.backends import default_backend
except ImportError:
    print("Error: 'cryptography' library not found.")
    print("Please install it using: pip install cryptography")
    sys.exit(1)

def generate_keys():
    print("Generating RSA-2048 keys...")
    
    # Generate private key
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )

    # Save private key
    pem_private = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    )
    
    with open("private_key.pem", "wb") as f:
        f.write(pem_private)
    print("Saved 'private_key.pem' (KEEP THIS SAFE!)")

    # Extract public key
    public_key = private_key.public_key()
    pem_public = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    )

    # Format as C header
    c_header = "// Public key for OTA signature verification\n"
    c_header += "// Generated by generate_keys.py\n\n"
    c_header += "const uint8_t PUBLIC_KEY[] PROGMEM = {\n"
    
    # Add null terminator implicitly by using the generated bytes? 
    # Original bin_signing.py adds a null byte at the end sometimes, 
    # but the C++ generic code often just takes the array. 
    # Let's match typical hex output.
    
    hex_array = []
    for byte in pem_public:
        hex_array.append(f"0x{byte:02x}")
        
    # Append 0x00 at the end as some verifiers expect null-terminated string/bytes
    hex_array.append("0x00") 
    
    # Format lines
    line_length = 0
    c_header += "  "
    for i, hex_val in enumerate(hex_array):
        c_header += hex_val + ", "
        line_length += len(hex_val) + 2
        if line_length > 80:
            c_header += "\n  "
            line_length = 0
            
    c_header = c_header.rstrip(", \n  ") + "\n};\n"
    c_header += f"const size_t PUBLIC_KEY_LEN = {len(pem_public) + 1};\n"

    with open("public_key.h", "w") as f:
        f.write(c_header)
    print("Saved 'public_key.h'")
    print("\nSuccess! Copy 'public_key.h' to your sketch folder if not already there.")

if __name__ == "__main__":
    generate_keys()
